name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Grant execute permission to ESLint
      - name: Grant execute permission to ESLint
        run: chmod +x ./node_modules/.bin/eslint

      # Step 5: Run ESLint for linting
      - name: Lint with ESLint
        run: npm run lint

      # Step 6: Run Jest tests
      - name: Test with Jest
        run: npm test
