name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'  # Nightly runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Update to a more recent version

    - name: Install dependencies
      run: |
        npm install

    - name: Lint with ESLint
      run: |
        npx eslint .

    - name: Test with Jest
      run: |
        npm test
