name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'  # Nightly runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Use a compatible Node.js version

    - name: Install dependencies
      run: |
        npm install

    - name: Install ESLint globally
      run: |
        npm install -g eslint

    - name: Lint with ESLint
      run: |
        eslint .

    - name: Test with Je
